AWSTemplateFormatVersion: '2010-09-09'
Description: 'Infraestructura base'

Resources:
  MiBucketS3:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'devops-bucket-${AWS::AccountId}'
      VersioningConfiguration:
        Status: Enabled

  MiInstanciaEC2:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0440d3b780d96b29d
      IamInstanceProfile: LabInstanceProfile
      Tags:
        - Key: Name
          Value: ServidorProyectoFinal

Outputs:
  InstanceId:
    Value: !Ref MiInstanciaEC2
  BucketName:
    Value: !Ref MiBucketS3
